README.md

add gogi at README.md

---

apps/api/urls.py
apps/api/views/v2.py
apps/core/backends.py
apps/core/forms.py
apps/core/management/commands/statistics.py
apps/core/urls.py
apps/core/views/profile.py
apps/dev/views.py
client/sparcsssov2.py
client/test.v2.py
sparcssso/settings.py
templates/account/service.html
templates/dev/service.html

- fix statistics module (done #101)
- use absolute path of db (done #100)
- minor api spec change
- move unregister features to client (done #103)
- prevent user modifying secret key (done #104)

Minor Bug Fix on SPARCS SSO Version 2

---

README.md
apps/core/backends.py

email is auto authed iff using KAIST id and email ends with @kaist.ac.kr

documentation update, email auto auth

---

.gitignore
apps/core/backends.py
apps/core/urls.py
apps/core/views/account.py
apps/core/views/auth.py
apps/core/views/general.py
apps/core/views/password.py
apps/core/views/profile.py
locale/ko/LC_MESSAGES/django.po
sparcssso/settings.py
static/css/main.css
templates/account/login.html
templates/account/profile.html
templates/base.html
templates/contact.html
templates/help.html
templates/stats.html

1. organize translation file; remove unused translation
2. add translation for contact page and others
3. add help faq; add mitm warning of KAIST
4. add local_settings file
5. remove unnecessary __init__, and utf8 encoding
6. refactor .gitignore

minor improvements on translations, project structures

---

apps/core/backends/service.py
client/sparcsssov2.py
client/test.v2.py
templates/account/service.html

remove timestamp and signature on unregister response

change spec of unregister - remove sign check

---

apps/core/views/general.py
apps/logger.py
locale/ko/LC_MESSAGES/django.po
sparcssso/settings.py
templates/error/csrf.html

- fix bug when non-sparcs users are trying to see stats
- fix bug that logger cannot write to file when using uwsgi
- add custom friendly csrf failure view
- sso will not pass csrf token to cookie

apply some hot fix; add custom csrf failure view

---

apps/api/urls.py
apps/api/views/v2.py
apps/core/admin.py
apps/core/backends/auth.py
apps/core/backends/service.py
apps/core/backends/signup.py
apps/core/backends/token.py
apps/core/forms.py
apps/core/management/commands/collect-logs.py
apps/core/management/commands/collect-stats.py
apps/core/management/commands/create-superuser.py
apps/core/management/commands/inspect.py
apps/core/management/commands/remove-users.py
apps/core/management/commands/send-mail.py
apps/core/urls.py
apps/core/views/account.py
apps/core/views/auth.py
apps/core/views/general.py
apps/core/views/password.py
apps/core/views/profile.py
apps/dev/urls.py
apps/dev/views.py
sparcssso/settings.py

Resolve issue #210 - remove all absolute imports

---

.flake8
.travis.yml
apps/core/backends/__init__.py
apps/core/backends/service.py
apps/core/management/commands/send-mail.py
client/sparcsssov2.py
client/test.v2.py
package-lock.json
package.json
static/js/stats.js

- Check both Python and JS lint
- Change Python import style from edited to pycharm
- Increase max line length from 80 to 120

Add Travis CI

---

requirements.txt

- refer to the security issue: https://docs.djangoproject.com/en/dev/releases/1.11.15/

Upgrade Django to 1.11.16

---

apps/core/views/general.py

Fix bug: incorrect docs status

---

package-lock.json
package.json
requirements.txt

by vulnerability reports
node version: v6 -> v8

Upgrade requests, django and node packages

---

apps/core/views/account.py
templates/account/base.html
templates/account/signup/main.html
templates/api/base.html
templates/base.html
templates/contact.html
templates/credits.html
templates/dev/base.html
templates/dev/main.html
templates/help.html
templates/main.html
templates/privacy.html
templates/stats.html
templates/terms.html

- use cloudflare cdn if possible
- use "defer" keyword if possible
- use protocol-relative url

Optimize stylesheets and scripts load performance

---

apps/core/backends/auth.py
apps/core/views/auth.py

Fix flake8 errors

---

apps/api/views/v2.py
sparcssso/urls.py

Return response as JSON for unsuccessful API calls

---

README.md
apps/api/serializers.py
apps/api/urls.py
apps/api/views/v2.py
apps/core/backends/decorator.py
apps/core/backends/sudo.py
apps/web/permissions.py
apps/web/serializers/notice.py
apps/web/serializers/profile.py
apps/web/serializers/service.py
apps/web/urls.py
apps/web/views/notice.py
apps/web/views/profile.py
package-lock.json
requirements.txt
sparcssso/settings/common.py
sparcssso/settings/development.py
sparcssso/settings/production.py
sparcssso/urls.py

- Django 2.2.19 업데이트 및 취약 dependency 업데이트 (Fixes #231)
- Django REST Framework 3.12.2 도입
- `/api/v2` 일부 뷰에 REST Framework 도입
현재 프로덕션에 `b33a9bd` 도입하여 정상 작동 확인하였습니다.
- **Testing**: Client 코드로 E2E pytest 추가할 예정입니다.
- `token/info` 등 Response에 Serializer 사용

Django REST Framework 도입

---

apps/api/serializers.py
apps/api/views/v2.py
apps/core/backends/decorator.py
apps/web/views/notice.py
apps/web/views/profile.py
requirements.txt
sparcssso/settings/development.py
sparcssso/settings/production.py

- Pillow==8.1.1
- urllib==1.26.4
- jinja2==2.11.3

Update insecure dependencies

---

apps/api/views/v2.py
tests/test_api.py

TokenRequireView, TokenInfoView의 각종 SuspiciousOperation에 대한 테스트를 추가합니다.

Add tests for API v2 edge cases

---

apps/core/backends/decorator.py
requirements.txt

Updates the following packages:
- Django 2.2.19 -> 3.1.8
- djangorestframework 3.12.2 -> 3.12.4

Update to Django 3.1 (#261)

---

apps/core/backends/decorator.py
apps/core/backends/sudo.py

Fix sudo check logic

---

package-lock.json
package.json

Update eslint dependencies
